%ifndef LINCOM
%define LINCOM 0
%endif

%if !DOS
%ifndef X32
BITS 32
%define X32 0
%endif
%endif

%ifndef DYN
%define DYN 0
%endif

%ifidn __OUTPUT_FORMAT__, bin
	%if !LINCOM
		%assign ELF_CUSTOM 1
	%else
		%assign ELF_CUSTOM 0
		org 0x10000
	%endif
%else
%assign ELF_CUSTOM 0
%endif

%macro setpos 1-2 FILL
	times $$-$+%1 %2
%endmacro

EXTERN _start

%ifndef ELF_OFFSET
%define ELF_OFFSET 3
%endif

%ifndef START
%define START _start - ELF_OFFSET
%endif

%if ELF_CUSTOM
%warning BIN format
;%macro BASE 1
%define BASE org
;	org %1
;%endmacro
%define	ELF_ALLINONE 0
%ifndef EOFF
%define EOFF 0
%endif

%macro ELF 0-1
	%ifndef MACHINE
	%define MACHINE 3
	%endif
		_ehdr:
		db	0x7F, "ELF"
		_phdr:
		dd	1
		_off:
		%if EOFF < 0
			dd	-(EOFF), $$	; vaddr
		%elif EOFF != 0
			dd	EOFF, $$ + EOFF	; vaddr
		%else
			dd	EOFF, $$	; vaddr
		%endif
		_e_type:
		%if DYN == 1
			dw	3
		%else
			dw	2
		%endif
		;dw	3
		_e_machine:
		%if X32 == 1
			dw	62
		%else
			dw	MACHINE
		%endif
		_filesz:
		dd	START			; garbage/filesz
		_start_memsz:
		dd	START			; start/memsz
_start:
		dd	4
	%if %0 == 1
		ELF_PHDR 1
	%endif
%endmacro

; add any parameter to add the jump around/safe value at the end
; increases file size by 1 byte
%macro ELF_PHDR 0-3
	%if !ELF_ALLINONE
		%if %0 == 3
			times $$-$+41   %3
			db	%2
		%elif %0 == 2
			times $$-$+41   nop
			db	%2
		%elif %0 == 1
			times $$-$+41   nop
			db	169
		%else
			times $$-$+42   nop
		%endif

		%if %0 > 0
			dw	0x20, 1
		%else
			db	0x20, 0, 1
		%endif
	%endif
	%define ELF_ALLINONE 1
%endmacro
%else
%warning ELF format
[section .text align=1]

%unmacro ELF 0-1
%macro ELF 0-1
_start:
%endmacro
%unmacro ELF_PHDR 0-2
%macro ELF_PHDR 0-2
%endmacro
%unmacro BASE 1
%macro BASE 1
	dw	%1/256
	db	%1/(256*256*256)
	dd	4
%endmacro
%endif
