%assign REG_OPT_LEVEL 4

%use ifunc

%ifndef	REG_ASSERT
%define	REG_ASSERT 0
%endif

%ifndef	ENABLE_LEA
%assign	ENABLE_LEA 0
%endif
%assign lea_scale 0
%assign lea_disp 0
%assign LEA_PERPLEXITY 0
%ifndef	USELEA
%assign	USELEA 1
%endif
; Optimization levels:
; Old:
; REG_SIMPLE: always use MOV
; no option: set register without assuming previous contents. rget always returns -1
; REG_OPT: use previous register value to set new value
; REG_SEARCH: search other registers for matching values, or registers == 0 for 3-byte lea
;
; New levels:
; 0 - always use MOV
; 1 - MOV or XOR r,r
; 2 - set without assuming previous content
; 3 - use previous content of register
; 4 - search other registers for match, or for zero registers
; 5 - search other register for offset up to imm8, or reg = other_reg * n
; 6 - lea with n*other_reg+off, or n*other_reg1+other_reg2, or n*other_reg1+other_reg2+off
;
; TODO:
; optimize putting values on stack. Only "push0" so far
;

%ifndef REG_OPT
%define REG_OPT 0
%endif

%ifndef REG_SEARCH
%define REG_SEARCH 0
%endif

%define reg_search_match 0
%define reg_search_zero 0

%imacro reg_assert 2-3.nolist ""
	%if !REG_ASSERT
		; do nothing
	%elif %2 == -2
		%warning ASSERT %1 =< 0xFF
		; 8 bit
		assert %1, 0xffffff00, 1, %strcat(" =< 0xFF",%3)
	%elif %2 == -3
		%warning ASSERT %1 =< 0xFFFF
		; 16 bit
		assert %1, 0xffff0000, 1, %strcat(" =< 0xFFFF",%3)
	%elif %2 == -4
		%warning ASSERT %1 > 0
		; positive signed integer
		assert %1, %1, 2, %strcat(" > 0",%3)
	%elif 0 && %2 == 0
		%warning ASSERT %1 == 0
		assert %1, %1, 1, %strcat(" == 0",%3)
	%elif %2 < 0
		; undefined val. nothing to check
	%else
		%warning ASSERT %1 == %2
		; defined number
		assert %1, %2, '', %strcat(" == ",%str(%2),%3)
	%endif

%endmacro

%ifndef ASSERT_SEGFAULT
%define ASSERT_SEGFAULT 0
%endif

%if __?BITS?__ == 64
	%define embiggen(a)  %tok(%strcat("r",%substr(a,2,2)))
%else
	%define embiggen(a)  a
%endif

%imacro OLDassert 2-4 0.nolist
	;%warning ASSERT %1 == %2, %3
	;%define %%jecx (%isidn(%1,ecx) && %isidn(%2,ecx) && %3 == 1)
	%%assert:
	%define %%jecx (%isidn(%1,ecx) && %2 == 0 && %isidn(%3,) )
	%if 0 && %%jecx
		jecxz	%%assert_end
	%else
		pushf
		%if   %3 == 0
			%if %2 == 0
				test	%1, %1
			%else
				cmp	%1, %2
			%endif
		%else
			test	%1, %2
		%endif
		%if %3 == 2
			jns	%%assert_end
			;js	ERRHLT
		%else
			je	%%assert_end
			;js	ERRHLT
		%endif
	%endif

	%if ASSERT_SEGFAULT
		; adjust by one to account for popf, except if jecxz
		mov [%%assert_end+!%%jecx], eax
	%else
		%strcat assert_string %str(__FILE__) ":" %str(__LINE__) " " %str(%1) %4
		;%strcat assert_string %str(__LINE__) " " %str(%1) %4 `\n`
		%strlen assert_strlen assert_string
		;%assign assert_strlen assert_strlen - 1
		%if 0
			reg
			inline_str assert_string
			; we can't use any macros here, because they would also use asserts again
			push	4
			pop	embiggen(eax)
			push 	2
			pop	embiggen(ebx)
			pop	embiggen(ecx)
			push	assert_strlen
			pop	embiggen(edx)
			int	0x80
			int3
		%else
			[section .text.assert]
			%%assert_code:
			reg
			inline_str assert_string
			; we can't use any macros here, because they would also use asserts again
			push	4
			pop	embiggen(eax)
			push 	2
			pop	embiggen(ebx)
			pop	embiggen(ecx)
			push	assert_strlen
			pop	embiggen(edx)
			int	0x80
			int3
			__?SECT?__
			jmp	%%assert_code

		%endif
	%endif

	%if !%%jecx
		popf
	%endif
	%%assert_end:
%endmacro

%imacro OLD2assert 2-4 0.nolist

	%strcat assert_string %str(__FILE__) ":" %str(__LINE__) " " %str(%1) %4
	;%strcat assert_string %str(__LINE__) " " %str(%1) %4 `\n`
	%strlen assert_strlen assert_string
	;%assign assert_strlen assert_strlen - 1
	[section .rodata align=1 strings merge]
	%%assert_rodata: db assert_string
	__?SECT?__

	[section .text.assert follows=.text]
	%%assert_code:
	reg
	push	4
	pop	embiggen(eax)
	push 	2
	pop	embiggen(ebx)
	taint	ecx
	mov	ecx, %%assert_rodata
	push	assert_strlen
	pop	embiggen(edx)
	int	0x80
	int3
	__?SECT?__

	%%assert:
	pushf

	%if   %3 == 0
		cmp	%1, %2
	%else
		test	%1, %2
	%endif
	%if %3 == 2
		;jns	%%assert_end
		js	%%assert_code
	%else
		;je	%%assert_end
		jne	%%assert_code
	%endif

	popf
	%%assert_end:
%endmacro

%imacro assert 2-4 0.nolist

%if !DOS
	%strcat assert_string %str(__FILE__) ":" %str(__LINE__) " " %str(%1) %4
	;%strcat assert_string %str(__LINE__) " " %str(%1) %4 `\n`
	%strlen assert_strlen assert_string

	[section .rodata]
	%%assert_rodata: db assert_string
	__?SECT?__
%endif

;; XXX NO MACROS OF ANY KIND ALLOWED HERE! XXX
; this is akin to an exception handler, and it runs right in the middle
; of e.g. the "set" macro. Internal state *will* be messed up if you do.
	[section .text.assert follows=.text]
	%%assert_%[%1]_%[%2]:
	pushf

	%if   %3 == 0
		cmp	%1, %2
	%else
		test	%1, %2
	%endif
	%if %3 == 2
		js	%%fail
	%else
		jne	%%fail
	%endif

	popf
	;push 0	  ; overwite the flags with null
	;add esp,4 ; and fix up stack pointer
	;mov dword [esp-4], 0
	ret

	%%fail:
%if !DOS
	reg
	push	4
	pop	eax
	push 	2
	pop	ebx
	mov	ecx, %%assert_rodata
	push	assert_strlen
	pop	edx
	int	0x80
	int3
%else
	;mov	[sp], ax
	;pop	ax
	reg
	int	0x20
%endif

;; XXX END OF NO MACRO SECTION XXX
	__?SECT?__

	call	%%assert_%[%1]_%[%2]
%endmacro

%define reg_fromzero 0
%define reg_keepflags 0
%define reg_stack 1
%define reg_inc 1
%define zero_seg 1
%assign reg_notneg 0

%imacro zero 1-*.nolist
	%assign zero_eax 0
	%assign zero_ebx 0
	%assign zero_ecx 0
	%assign zero_edx 0

	%assign zero_count 0
	%rep %0
		%if   %isidn(%1, eax) && reg_eax_val != 0
			%assign zero_eax 1
		%elif %isidn(%1, ebx) && reg_ebx_val != 0
			%assign zero_ebx 1
		%elif %isidn(%1, ecx) && reg_ecx_val != 0
			%assign zero_ecx 1
		%elif %isidn(%1, edx) && reg_edx_val != 0
			%assign zero_edx 1
		%endif
	%rotate 1
	%endrep
	
	findzero
	;%warning findzero reg_zero

	;%warning ZERO zero_eax zero_ebx zero_ecx zero_edx
	%if zero_eax && zero_ebx && zero_ecx && zero_edx
		dbg 3, zero abcd, using cpuid
		lahf
		cpuid				; 3 bytes
		rset eax, 0
		rset ebx, 0
		rset ecx, 0
		rset edx, 0
	%elif zero_eax && zero_edx && %isnidn(reg_zero,"")
		dbg 3, zero ad, using mul reg_zero
		mul %tok(reg_zero)		; 2 bytes
		rset eax, 0
		rset edx, 0
	%endif

	%rep %0
		rget_maybe eax
		%assign eax_notneg reg_notneg
		rget_maybe %1

		%if reg_val == 0
			rget	%1
			dbg 3, register %1 already zero
		%elif %isidn(reg_str,"edx") && eax_notneg
			rget	eax
			dbg 3, zero edx and eax<0x80000000, using cdq
			cdq
		%elif zero_seg || reg_keepflags
			mov	%1, fs
		%else
			xor	%1, %1
		%endif
		rset %1, 0
	%rotate 1
	%endrep
%endmacro

%macro rdump arg(0)
	%warning DUMP
	%warning eax: reg_eax_val
	%warning ebx: reg_ebx_val
	%warning ecx: reg_ecx_val
	%warning edx: reg_edx_val
	%warning ebp: reg_ebp_val
	%warning esi: reg_esi_val
	%warning edi: reg_edi_val
	%warning esp: reg_esp_val
%endmacro

%macro rdump1 0
	%warning reg_eax_val reg_ebx_val reg_ecx_val reg_edx_val reg_ebp_val reg_esi_val reg_edi_val reg_esp_val
%endmacro

%macro rinit 0
	%assign reg_eax_val 0
	%assign reg_ebx_val 0
	%assign reg_ecx_val 0
	%assign reg_edx_val 0
	%assign reg_esi_val 0
	%assign reg_edi_val 0
	%assign reg_ebp_val 0
	%assign reg_esp_val -1
%endmacro

%macro rtaint 0
	%assign reg_eax_val -1
	%assign reg_ebx_val -1
	%assign reg_ecx_val -1
	%assign reg_edx_val -1
	%assign reg_ebp_val -1
	%assign reg_esi_val -1
	%assign reg_edi_val -1
	%assign reg_esp_val -1

	%assign reg_eax_val_low -1
	%assign reg_ebx_val_low -1
	%assign reg_ecx_val_low -1
	%assign reg_edx_val_low -1
	%assign reg_ebp_val_low -1
	%assign reg_esi_val_low -1
	%assign reg_edi_val_low -1
	%assign reg_esp_val_low -1

	%assign reg_eax_val_high -1
	%assign reg_ebx_val_high -1
	%assign reg_ecx_val_high -1
	%assign reg_edx_val_high -1
	%assign reg_ebp_val_high -1
	%assign reg_esi_val_high -1
	%assign reg_edi_val_high -1
	%assign reg_esp_val_high -1

	%assign reg_eax_val_16 -1
	%assign reg_ebx_val_16 -1
	%assign reg_ecx_val_16 -1
	%assign reg_edx_val_16 -1
	%assign reg_ebp_val_16 -1
	%assign reg_esi_val_16 -1
	%assign reg_edi_val_16 -1
	%assign reg_esp_val_16 -1
%endmacro

%macro reg_mark 0
	%assign reg_eax_val -1001
	%assign reg_ebx_val -1002
	%assign reg_ecx_val -1003
	%assign reg_edx_val -1004
	%assign reg_esi_val -1005
	%assign reg_edi_val -1006
	%assign reg_ebp_val -1007
	%assign reg_esp_val -1008
%endmacro

rtaint

%macro reg_search_single 2.nolist
	rget_maybe %2
	%if %1 == reg_val
		;%warning FOUND MATCH: %2 == %1
		%define reg_search_match %2
	%endif
%endmacro

%macro reg_search 1.nolist
	%define reg_search_match 0
	reg_search_single 0, eax
	reg_search_single 0, ebx
	reg_search_single 0, ecx
	reg_search_single 0, edx
	reg_search_single 0, esi
	reg_search_single 0, edi
	reg_search_single 0, ebp
	reg_search_single 0, esp
	%xdefine reg_search_zero reg_search_match

	%define reg_search_match 0
	reg_search_single %1, eax
	reg_search_single %1, ebx
	reg_search_single %1, ecx
	reg_search_single %1, edx
	reg_search_single %1, esi
	reg_search_single %1, edi
	reg_search_single %1, ebp
	reg_search_single %1, esp

%endmacro

%macro rmov 2
	%defstr reg_str %2

	%if %isidn(reg_str, "eax")
		rget %2
		rset %1, reg_val
	%elif %isidn(reg_str, "ebx") 
		rget %2
		rset %1, reg_val
	%elif %isidn(reg_str, "ecx") 
		rget %2
		rset %1, reg_val
	%elif %isidn(reg_str, "edx") 
		rget %2
		rset %1, reg_val
	%elif %isidn(reg_str, "esp") 
		rget %2
		rset %1, reg_val
	%elif %isidn(reg_str, "ebp") 
		rget %2
		rset %1, reg_val
	%elif %isidn(reg_str, "esi") 
		rget %2
		rset %1, reg_val
	%elif %isidn(reg_str, "edi") 
		rget %2
		rset %1, reg_val
	%else
		%warning rmov: no such register %2
		taint %1
	%endif
%endmacro

%imacro ychg arg(2)
	%ifidn %1,%2
		%warning %?: same register, nothing to do
	%else
		rget    %1
		%assign yval1 reg_val
		rget    %2
		%assign yval2 reg_val

		;%if yval1 > 0 && yval2 > 0 && yval1 != yval2
		%if yval1 != yval2 || yval1 < 0 || yval2 < 0
			xchg    %1, %2
			rset    %1, yval2
			rset    %2, yval1
		%else
			%warning %?: same value, nothing to do
		%endif
	%endif

%endmacro

%macro save arg(2)
	dbg 2, SAVE register %1
	rset	%1, -100 - %2
%endmacro

%macro rset 2.nolist
	dbg 3, register %1 == %2
	%defstr reg_str %1
	rget_maybe %1
	%if reg_val <= -100
		dbg 2, SAVE value destroyed: reg_val, %1 == %2
	%endif

	%if %2 > -1
		%assign reg_new_low  (%2 & 0xFF)
		%assign reg_new_high (%2 & 0xFF00)
		%assign reg_new_16   (%2 & 0xFFFF)
	%else
		%assign reg_new_low  -1
		%assign reg_new_high -1
		%assign reg_new_16   -1
	%endif

	__rset_raw reg_str, %2, reg_new_low, reg_new_high, reg_new_16

	%if REG_OPT
		; XXX check value directly when we assert it
		reg_assert %1, %eval(%2), " S"
	%endif
	;rdump
%endmacro

%macro __rset_raw 5.nolist
	%if %isidn(%1, "eax")
		%assign reg_eax_val		%2
		%assign reg_eax_val_low		%3
		%assign reg_eax_val_high	%4
		%assign reg_eax_val_16		%5
	%elif %isidn(%1, "ebx")
		%assign reg_ebx_val		%2
		%assign reg_ebx_val_low		%3
		%assign reg_ebx_val_high	%4
		%assign reg_ebx_val_16		%5
	%elif %isidn(%1, "ecx")
		%assign reg_ecx_val		%2
		%assign reg_ecx_val_low		%3
		%assign reg_ecx_val_high	%4
		%assign reg_ecx_val_16		%5
	%elif %isidn(%1, "edx")
		%assign reg_edx_val		%2
		%assign reg_edx_val_low		%3
		%assign reg_edx_val_high	%4
		%assign reg_edx_val_16		%5
	%elif %isidn(%1, "esi")
		%assign reg_esi_val		%2
		%assign reg_esi_val_low		%3
		%assign reg_esi_val_high	%4
		%assign reg_esi_val_16		%5
	%elif %isidn(%1, "edi")
		%assign reg_edi_val		%2
		%assign reg_edi_val_low		%3
		%assign reg_edi_val_high	%4
		%assign reg_edi_val_16		%5
	%elif %isidn(%1, "ebp")
		%assign reg_ebp_val		%2
		%assign reg_ebp_val_low		%3
		%assign reg_ebp_val_high	%4
		%assign reg_ebp_val_16		%5
	%elif %isidn(%1, "esp")
		%assign reg_esp_val		%2
		%assign reg_esp_val_low		%3
		%assign reg_esp_val_high	%4
		%assign reg_esp_val_16		%5
	%else
		%error no such register "%1"
	%endif
%endmacro

%macro reg_push arg(0)
	%push	reg_context
	;rdump

	%assign %$old_reg_eax_val reg_eax_val 
	%assign %$old_reg_ebx_val reg_ebx_val 
	%assign %$old_reg_ecx_val reg_ecx_val 
	%assign %$old_reg_edx_val reg_edx_val 
	%assign %$old_reg_esi_val reg_esi_val 
	%assign %$old_reg_edi_val reg_edi_val 
	%assign %$old_reg_ebp_val reg_ebp_val 
	%assign %$old_reg_esp_val reg_esp_val 
%endmacro

%macro	reg_pop 0
	%ifnctx reg_context
		%warning %?: not in reg_context
	%endif

	%assign reg_eax_val %$old_reg_eax_val 
	%assign reg_ebx_val %$old_reg_ebx_val 
	%assign reg_ecx_val %$old_reg_ecx_val 
	%assign reg_edx_val %$old_reg_edx_val 
	%assign reg_esi_val %$old_reg_esi_val 
	%assign reg_edi_val %$old_reg_edi_val 
	%assign reg_ebp_val %$old_reg_ebp_val 
	%assign reg_esp_val %$old_reg_esp_val 

	%pop	reg_context
%endmacro

%macro	reg_commit arg(0)
	%ifnctx reg_context
		%warning %?: not in reg_context
	%endif

	dbg 3, COMMIT
	dbg 4, eax: reg_eax_val, was %$old_reg_eax_val
	dbg 4, ebx: reg_ebx_val, was %$old_reg_ebx_val
	dbg 4, ecx: reg_ecx_val, was %$old_reg_ecx_val
	dbg 4, edx: reg_edx_val, was %$old_reg_edx_val
	dbg 4, esi: reg_esi_val, was %$old_reg_esi_val
	dbg 4, edi: reg_edi_val, was %$old_reg_edi_val
	dbg 4, ebp: reg_ebp_val, was %$old_reg_ebp_val
	dbg 4, esp: reg_esp_val, was %$old_reg_esp_val

	%pop	reg_context
%endmacro

%macro findzero 0
	%defstr reg_zero
	%if reg_eax_val == 0
		%defstr reg_zero eax
	%elif reg_ebx_val == 0
		%defstr reg_zero ebx
	%elif reg_ecx_val == 0
		%defstr reg_zero ecx
	%elif reg_edx_val == 0
		%defstr reg_zero edx
	%elif reg_esp_val == 0
		%defstr reg_zero esp
	%elif reg_ebp_val == 0
		%defstr reg_zero ebp
	%elif reg_esi_val == 0
		%defstr reg_zero esi
	%elif reg_edi_val == 0
		%defstr reg_zero edi
	%endif
%endmacro

%macro rassert arg(0)
	rget eax
	rget ebx
	rget ecx
	rget edx
	rget esi
	rget edi
	rget ebp
	rget esp
%endmacro

%macro rget arg(1)
	rget_maybe %1
	%if REG_OPT
		reg_assert %1, reg_val, " G"
	%endif
%endmacro

%macro rget_maybe arg(1)
%if REG_OPT
	;%warning FOO __LINE__ %1
	%defstr reg_str %1

	%if %isidn(reg_str, "eax")
		%assign reg_val reg_eax_val
	%elif %isidn(reg_str, "ebx") 
		%assign reg_val reg_ebx_val
	%elif %isidn(reg_str, "ecx") 
		%assign reg_val reg_ecx_val
	%elif %isidn(reg_str, "edx") 
		%assign reg_val reg_edx_val
	%elif %isidn(reg_str, "esp") 
		%assign reg_val reg_esp_val
	%elif %isidn(reg_str, "ebp") 
		%assign reg_val reg_ebp_val
	%elif %isidn(reg_str, "esi") 
		%assign reg_val reg_esi_val
	%elif %isidn(reg_str, "edi") 
		%assign reg_val reg_edi_val
	%else
		%error no such register %1
	%endif

	%if reg_val > -1
		%assign reg_defined 1
	%else
		%assign reg_defined 0
	%endif

	%if reg_val == -2 || (reg_defined && reg_val < 256)
		%assign reg_8bit 1
	%else
		%assign reg_8bit 0
	%endif

	%if reg_val == -3 || reg_8bit || (reg_defined && reg_val < 65536)
		%assign reg_16bit 1
	%else
		%assign reg_16bit 0
	%endif

	%if reg_val == -4 || reg_8bit || reg_16bit || (reg_defined && reg_val < 0x80000000)
		%assign reg_notneg 1
	%else
		%assign reg_notneg 0
	%endif
	; XXX uncomment to do excessive assertions again
	;reg_assert %1, reg_val, " ex"

	%define reg_vprefix   %strcat("reg_",%1,"_val_")
	%assign reg_val_high %tok(%strcat(reg_vprefix,"high"))
	%assign reg_val_low  %tok(%strcat(reg_vprefix,"low"))
	%assign reg_val_16   %tok(%strcat(reg_vprefix,"16"))
%else
	%assign	reg_val -1
	%assign	reg_defined 0
	%assign	reg_8bit 0
	%assign	reg_16bit 0
%endif
%endmacro

; mark registers as "unknown value"
%imacro taint arg(1-*)
	%rep %0
		;%warning %1 tainted: -1
		rset %1, -1
	%rotate 1
	%endrep
%endmacro

; mark lower 8 bits as tainted
%macro taint8 arg(1)
	rget_maybe	%1
	%if reg_8bit
		rset	%1, -2
	%elif reg_16bit
		rset	%1, -3
	%elif reg_val < -1000
		rset	%1, reg_val - 10
	%else
		rset	%1, -1
	%endif
%endmacro

; mark lower 16 bits as tainted
%macro taint16 arg(1)
	rget_maybe	%1
	%if reg_16bit
		rset	%1, -3
	%elif reg_val < -1000
		rset	%1, reg_val - 100
	%else
		rset	%1, -1
	%endif
%endmacro

; register is strictly less than its previous value
; handy for loops where a value gets smaller through dec, div or similar
%macro taintlt arg(1)
	rget_maybe	%1
	%if reg_defined && reg_val == 0
		rset	%1, -1
		;%else
			;rset	%1, reg_val - 1
		;%endif
	%elif reg_8bit
		rset	%1, -2
	%elif reg_16bit
		rset	%1, -3
	%elif reg_val < -1000
		rset	%1, reg_val - 10
	%else
		rset	%1, -1
	%endif
%endmacro

; check if valid register name, generate 8b/16b register names
%imacro regparse 1
	%defstr reg_str %1

	%substr reg_prefix reg_str 1,1
	%if !(%isidn(reg_prefix,'e') || %isidn(reg_prefix,'r'))
		%fatal 'set' with illegal register, %1, reg_prefix != 'e', pass __PASS__
	%endif

	%substr reg_id   reg_str 2,1
	%substr reg_type reg_str 3,1

	%ifidn reg_type,'x'
		%assign reg_var 1
		%strcat reg_low  reg_id "l"
		%strcat reg_high reg_id "h"

		%deftok reg_low  reg_low
		%deftok reg_high reg_high
	%else
		%assign reg_var 0
		%define reg_low  INVALID
		%define reg_high INVALID
	%endif
	%strcat reg_leg  reg_id reg_type
	%deftok reg_leg  reg_leg

	%ifidn reg_str,'esp'
		%assign reg_notesp 0
	%else
		%assign reg_notesp 1
	%endif
%endmacro

%macro regparse_small 1
	%defstr reg_str %1
	%if %strlen(reg_str) != 2
		%error invalid reg for regparse_small: reg_str
	%endif

	%substr reg_id   reg_str 1,1
	%substr reg_size reg_str 2,1

	%if %isidn(reg_size,'x') || %isidn(reg_size,'l') || %isidn(reg_size,'h')
		%assign reg_var 1
		%strcat reg_low  reg_id "l"
		%strcat reg_high reg_id "h"

		%deftok reg_low  reg_low
		%deftok reg_high reg_high
		%define reg_final "x"
	%else
		%assign reg_var 0
		%define reg_low  INVALID
		%define reg_high INVALID

		%xdefine reg_final reg_size
		%define	reg_size 'x'
	%endif

	;%strcat reg_leg  reg_id reg_final
	;%deftok reg_leg  reg_leg
	%deftok reg_leg  %strcat(reg_id,reg_final)
	%deftok reg_full %strcat('e',reg_leg)

	dbg 0, PARSESMAL0 size reg_size
	%if %isidn(reg_size,'l')
		%define reg_type low
	%elif %isidn(reg_size,'h')
		%define reg_type high
	%else
		%define reg_type 16
	%endif
	dbg 0, PARSESMALL type reg_type
%endmacro

%macro rset_small arg(2)
	regparse_small %1
	rget_maybe reg_full
%endmacro

%macro set2 arg(2)
	regparse_small %1
	%if %isid(%2) || 0
		%ifidn %1,%2
			; nothing
		%else
			mov	%1, %2
			; XXX track values
			taint16	reg_full
		%endif
	%else
	%endif
%endmacro

%macro set_small arg(2)
	regparse_small %1
	%if %isid(%2) || 0
		%ifidn %1,%2
			; nothing
		%else
			mov	%1, %2
			; XXX track values
			taint16	reg_full
		%endif
	%else
	%xdefine set_type reg_type
	rget_maybe reg_full
	dbg 0, PREV val reg_val	hi	reg_val_high	 lo	reg_val_low	leg	reg_val_16
	dbg 0, RR val %2 type set_type

	%if reg_val >= 0
		%assign	reg_val_high16		(reg_val & 0xffff0000)
	%elif reg_val == -3
		%assign	reg_val_high16		0
	%elif reg_val == -2
		%assign	reg_val_high16		0
		%assign	reg_val_high		0
	%else
		%assign	reg_val_high16		-1
		; unk
	%endif

	%if %isidn(set_type,low)
		dbg 0, low
		%assign reg_new_low	%2
		%assign reg_new_high	reg_val_high
		%assign reg_new_16	(reg_val_high<<8 + reg_new_low)
		%assign reg_old		reg_val_low
		%assign reg_new		reg_new_low
	%elif %isidn(set_type,high)
		dbg 0, high
		%assign reg_new_low	reg_val_low
		%assign reg_new_high	%2
		%assign reg_new_16	(reg_new_high<<8 + reg_val_low)
		%assign reg_old		reg_val_high
		%assign reg_new		reg_new_high
	%elif %isidn(set_type,16)
		dbg 0, reg16
		%assign reg_new_16	%2
		%assign reg_new_low	(reg_new_16 & 0xff)
		%assign reg_new_high	(reg_new_16 & 0xff00)>>8
		%assign reg_old		reg_val_16
		%assign reg_new		reg_new_16
	%else
		%error unknown reg type set_type
	%endif

	%if reg_val_high16 >= 0
		%assign	reg_new_val		(reg_val_high16 | reg_new_16)
	%else
		%assign	reg_new_val		reg_val
	%endif
	dbg 0, AFTR val reg_new_val hi reg_new_high lo reg_new_low leg reg_new_16
	;rset_small %1, %2
	;rget_maybe reg_full
	;regparse_small %1
	dbg 0, smallset mov %1, %2:   reg_old -> reg_new
	%if reg_old != reg_new
		%if 0 && %isidn(set_type,16) && %2 < 256 && reg_val_high == 0
			mov	reg_low, %2
		%else
			mov	%1, %2
		%endif
	%else
		dbg 0, smallset same value, skipping mov
	%endif
	;dbg 0, VAR reg_var FULL reg_full LOW reg_low HIGH reg_high LEG reg_leg
	__rset_raw %str(reg_full), reg_new_val, reg_new_low, reg_new_high, reg_new_16
	%endif
%endmacro

; parse 32b integer to unsigned/signed variants
%imacro int32 1

	%if %1 < 0
		%assign uint32 (0x100000000 + %1)
		;%assign uint32 (~%1)
	%else
		%assign uint32 (+%1 % 0xFFFFFFFF)
	%endif

	%if %1 > 0x7FFFFFFF
		%assign sint32 -(-%1 % 0xFFFFFFFF)
	%else
		%assign sint32 %1
	%endif
%endmacro

%assign rsave 0

; set register, assuming it currently contains 0
%imacro setfz arg(2)
	regparse %1

	int32 %2
	dbg 4, LOGARITHM %eval(ilog2f(uint32)) == %eval(ilog2c(uint32))

	%assign reg_delta uint32 - reg_val
	dbg 3, setfz %1 old: reg_val, new: uint32, delta: reg_delta

	%if reg_val == uint32
		dbg 4, same value, skipping
	%elif %2 == 0
		%assign rsave rsave+5
						;0 bytes
	%elif %2 == 1 && !reg_keepflags && reg_inc
		%assign rsave rsave+4
		inc	%1			;1 byte
	%elif sint32 == -1 && !reg_keepflags && reg_inc
		%assign rsave rsave+4
		dec	%1			;1 byte
	%elif reg_var && uint32 < 256
		%assign rsave rsave+3
		mov	reg_low, %2		;2 bytes
	%elif reg_var && uint32 % 256 == 0 && uint32 >= 256 && uint32 < 65536
		%assign rsave rsave+3
		mov	reg_high, %2/256	;2 bytes
	%elif uint32 == 0xFFFF && !reg_keepflags && reg_inc
		%assign rsave rsave+3
		dec	reg_leg			;2 bytes
	%elif ENABLE_LEA && lea_scale > 0
		dbg 0, %1, %2: lea search
		%assign rsave rsave+2		;3 bytes
		lea	%1, [lea_base + lea_scale * lea_index]
	%elif ENABLE_LEA && lea_disp != 0
		dbg 0, %1, %2: lea search disp
		%assign rsave rsave+2		;3 bytes
		lea	%1, [lea_dbase + lea_disp]
	%elif USELEA && !ENABLE_LEA && reg_notesp && sint32 < 128 && sint32 > -129
		%assign rsave rsave+2
		lea	%1, [%1+%2]		;3 bytes
	%elif reg_var && sint32 < 0 && sint32 >= -256 && !reg_keepflags && reg_inc
		%assign rsave rsave+2
		dec	%1
		mov	reg_low, (%2 & 0xFF)	;3 bytes
	; dec/mov reg_high 3b
	; mov reg_high/neg 4b
	; mov reg_high/not 4b
	%elif sint32 < 128 && sint32 > -129 && reg_stack
		%assign rsave rsave+2
		push	%2
		pop	%1			;3 bytes
	%elif sint32 < 128 && sint32 > -129 && !reg_keepflags
		%assign rsave rsave+2
		add	%1, %2			;3 bytes
	%elif uint32 == 0x00010000 && !reg_keepflags && reg_inc
		%assign rsave rsave+1
		dec	reg_leg
		inc	%1			;3 bytes
	%elif uint32 == 0x01000000 && !reg_keepflags && reg_inc
		%assign rsave rsave+1
		inc	%1
		bswap	%1			;3 bytes
	%elif uint32 == 0x80000000 && !reg_keepflags && reg_inc
		%assign rsave rsave+2
		inc	%1
		ror	%1, 1			;3 bytes
	%elif uint32 < 65536
		%assign rsave rsave+1
		mov	reg_leg, %2		;4 bytes
	%elif reg_var && sint32 >= 256 && sint32 < 512 && !reg_keepflags && reg_inc
		%assign rsave rsave+1
		dbg 4, %1: BLUBB
		inc	reg_high
		mov	reg_low, %2 - 256	;4 bytes
	%elif USELEA && !reg_notesp && sint32 < 128 && sint32 > -129
		%assign rsave rsave+1
		lea	%1, [%1+%2]		;4 bytes
	%elif reg_var && uint32 % 16777216 == 0
		%assign rsave rsave+1
		dbg 4, %1: highest byte
		mov	reg_low, %2/16777216
		bswap	%1			;4 bytes
	%elif reg_var && uint32 % 65536 == 0 && uint32 <= 0xFF0000
		%assign rsave rsave+1
		dbg 4, %1: secondhighest byte
		mov	reg_high, %2/65536
		bswap	%1			;4 bytes
	%elif ilog2f(uint32) == ilog2c(uint32) && !reg_keepflags && reg_inc
		%assign rsave rsave+1
		inc	%1
		shl	%1, ilog2f(uint32)	;4 bytes
	%elif uint32 == 0xFFFF0000 && !reg_keepflags && reg_inc
		%assign rsave rsave+1
		dec	reg_leg
		bswap	%1			;4 bytes
	%else
		mov	%1, %2			;5 bytes
	%endif
	;rset %1, uint32
%endmacro

%imacro __set_num 2;.nolist
	regparse %1
	int32 %2

	dbg 6, KEEPFLAGSn reg_keepflags

	%assign rsave_orig rsave
	rget %1
	%assign reg_delta uint32 - reg_val
	;rdump
	dbg 4, %1 old: reg_val, new: uint32/sint32, delta: reg_delta
	;reg_assert %1, reg_val	
	%if ENABLE_LEA
		leasearch uint32
	%endif
	%if REG_SEARCH
		reg_search uint32
		rget_maybe %1
		; TODO: rget again. excessive asserts due to rget
		%if reg_search_match != 0
			dbg 5, SEARCH FINAL MATCH reg_search_match
		;%else
		;	%warning NO MATCH
		%endif
	%else
		%assign reg_search_match 0
		%assign reg_search_zero 0
	%endif
	;%warning GGG  reg_search_zero != 0 && reg_notesp && sint32 < 128 && sint32 > -129
	dbg 6, KEEPFLAGS2
	%if 0
		%warning FOO
	%elif reg_keepflags
		dbg 6, BAR
	%else
		dbg 6, NO MATCH
	%endif
	dbg 6, KEEPFLAGS2B
	%if reg_val == uint32
		%assign rsave rsave+5
		dbg 4, same value, skipping
	%elif reg_val == 0
		dbg 4, %1, %2: from zero, going to setfz
		setfz	%1, %2
	%elif reg_defined && reg_delta == 1 && !reg_keepflags && reg_inc
		dbg 4, diff of 1, doing inc
		inc	%1	; 1 byte
	%elif reg_defined && reg_delta == -1 && !reg_keepflags && reg_inc
		dbg 4, diff of -1, doing dec
		dec	%1	; 1 byte
	%elif %2 == 0
		dbg 4, %1: zero (%1 reg_val uint32)
		%assign rsave rsave+3
		zero	%1	; 2 bytes
	%elif reg_var && reg_8bit && uint32 < 256
		%assign rsave rsave+3
		;%warning %1 old and new value < 256, doing 8bit op (%1 reg_val uint32)
		dbg 4, %1: 8bit (%1 reg_val uint32)
		mov	reg_low, %2	; 2 bytes
	%elif reg_search_match != 0
		rget	reg_search_match
		%assign rsave rsave+3
		dbg 4, %1: FROM_OTHER
		%ifndef USELEA
		%define USELEA 1
		%endif
		%if USELEA && !%isidn(reg_search_match,esp) && !%isidn(reg_search_match,ebp)
			lea	%1, [reg_search_match]	; 2 bytes
		%else
			mov	%1, reg_search_match	; 2 bytes
		%endif
		
	%elif ENABLE_LEA && lea_scale > 0
		dbg 0, %1, %2: lea_base+lea_index*lea_scale lea search
		%assign rsave rsave+2		;3 bytes
		lea	%1, [lea_base + lea_scale * lea_index]
	%elif ENABLE_LEA && lea_disp != 0
		dbg 0, %1, %2: lea search disp
		%assign rsave rsave+2		;3 bytes
		lea	%1, [lea_dbase + lea_disp]
	%elif sint32 == -1 && !reg_keepflags
		dbg 4, %1: minus one #2 (%1 reg_val uint32)
		; clears carry&overflow flags
		%assign rsave rsave+2
		or	%1, -1	; 3 bytes
	%elif sint32 == -1 && !reg_keepflags && reg_inc
		dbg 4, %1: minus one (%1 reg_val uint32)
		; leaves carry flag alone
		%assign rsave rsave+2
		zero	%1
		dec	%1	; 3 bytes
	%elif %2 == 1 && !reg_keepflags && reg_inc
		dbg 4, %1: one (%1 reg_val uint32)
		%assign rsave rsave+2
		zero	%1
		inc	%1	; 3 bytes
	%elif sint32 < 128 && sint32 > -129 && reg_stack
		dbg 4, %1: pushpop (%1 reg_val uint32)
		%assign rsave rsave+2
		push	%2
		;%fatal uggg oggg __?BITS?__
		pop	embiggen(%1)	; 3 bytes
	%elif USELEA && !ENABLE_LEA && reg_search_zero != 0 && reg_notesp && sint32 < 128 && sint32 > -129
		rget	reg_search_zero
		dbg 4, %1: FROM_OTHER zero
		%assign rsave rsave+2
		lea	%1, [reg_search_zero+%2]		;3 bytes
	%elif reg_var && uint32 < 256
		dbg 4, %1: reg_low (%1 reg_val uint32)
		%assign rsave rsave+1
		zero	%1	; 4 bytes
		mov	reg_low, %2	
	%elif reg_var && uint32 % 256 == 0 && uint32 >= 256 && uint32 < 65536
		dbg 4, %1: reg_high (%1 reg_val uint32)
		%assign rsave rsave+1
		zero	%1	; 4 bytes
		mov	reg_high, %2/256
	%elif uint32 == 0xFFFF && !reg_keepflags && reg_inc
		dbg 4, %1: 0xFFFF (%1 reg_val uint32)
		%assign rsave rsave+1
		zero	%1	; 4 bytes
		dec	reg_leg
	%elif %isidn(%1,eax) && sint32 == -103 && !reg_keepflags && reg_inc
		dbg 4, %1: -103 (%1 reg_val uint32)
		%assign rsave rsave+1
		zero	%1	; 4 bytes
		dec	%1
		das
	%elif %isidn(%1,eax) && sint32 == -503 && !reg_keepflags && reg_inc
		dbg 4, %1: -503 (%1 reg_val uint32)
		%assign rsave rsave+1
		zero	%1	; 4 bytes
		dec	%1
		aas
	%elif %isidn(%1,eax) && sint32 == -155 && !reg_keepflags && reg_inc
		dbg 4, %1: -155 (%1 reg_val uint32)
		%assign rsave rsave+1
		zero	%1	; 4 bytes
		dec	%1
		daa
	%elif %isidn(%1,eax) && sint32 == -65275 && !reg_keepflags && reg_inc
		dbg 4, %1: -65275 (%1 reg_val uint32)
		%assign rsave rsave+1
		zero	%1	; 4 bytes
		dec	%1
		aaa
	%elif reg_16bit && uint32 < 65536
		dbg 4, %1: 16bit (%1 reg_val uint32)
		%assign rsave rsave+1
		mov	reg_leg, %2		;4 bytes
	%else
		dbg 4, NO OTHER MATCH
		mov	%1, %2	; 5 bytes
	%endif

	dbg 6, KEEPFLAGS3
	%assign rbyte 5-(rsave-rsave_orig)
	dbg 4, COST: rbyte bytes %1 reg_val -> uint32/sint32
	dbg 4, CC %1 rbyte bytes: reg_val uint32 <- reg_eax_val reg_ebx_val reg_ecx_val reg_edx_val reg_ebp_val reg_esi_val reg_edi_val reg_esp_val
	rset %1, uint32
%endmacro

%ifndef REG_SIMPLE
%define REG_SIMPLE 0
%endif

%ifndef REG_DESTRUCTIVE
%define REG_DESTRUCTIVE 0
%endif

%imacro checkconstant 1
	%defstr %%name %1

	;%ifndef %[%1]
	;	%error %%name not defined
	;%endif

	%ifnnum %1
		%error %%name is not a number
	%endif

;	%ifstr reg_keepflags
;		%warning keepflags is str
;	%endif
;
;	%iftoken reg_keepflags
;		%warning keepflags is token
;	%endif
;
;	%ifid reg_keepflags
;		%warning keepflags is id
;	%endif
;
;	%ifempty reg_keepflags
;		%warning keepflags is empty
;	%endif
;	%ifnempty reg_keepflags
;		%warning keepflags is not empty
;	%endif
%endmacro

%imacro set arg(2)
	checkconstant reg_keepflags
	checkconstant reg_stack
	checkconstant REG_SEARCH
	checkconstant REG_OPT
	;token_info %1
	;token_info %2

	%ifidn %2,pop
		pop	%1
		taint	%1
	%elifidn %2,x
		; do nothing
	%elif REG_SIMPLE
		%if %1 != %2
			mov	%1, %2
		%endif
	%elifidn %2,$
		mov	%1, %2	; 5 bytes
		taint	%1
	%elifidn %2,$$
		mov	%1, %2	; 5 bytes
		taint	%1
	%elif %strlen(%1) == 2
		set_small %1, %2
	%elifnum %2
		__set_num %1, %eval(%2)
	%elifstr %2
		__set_num %1, %2
	%elifid %2
		%ifidn %1,%2
			; nothing
		%elif REG_DESTRUCTIVE && %isidn(%1,eax) && __?PASS?__ != 3
			ychg	%1, %2
		%else
			mov	%1, %2	; 2 bytes
			rmov	%1, %2
		%endif
	%else
		%error XXXXXXXXXXXXXXXXX ASSUMING CRITICAL EXPRESSION
	%endif
%endmacro

%imacro push0 arg(0)
	rpush 0
%endmacro

%imacro rpush 1
	%if %isnum(%1) || %isstr(%1)
		int32 %1
		reg_search uint32
		%if reg_search_match != 0
			%warning PUSH SEARCH FINAL MATCH reg_search_match
			push	%tok(reg_search_match)
		%else
			%warning PUSH SEARCH nomatch %1 uint32
			push	%1
		%endif
	%else
		push	%1
	%endif
%endmacro

%macro leasearch arg(1)
	%assign lea_scale 0
	%assign lea_disp 0
	; index
	%if !LEA_PERPLEXITY
		lea2 %1, eax
		lea2 %1, ebx
		lea2 %1, ecx
		lea2 %1, edx
		lea2 %1, esi
		lea2 %1, edi
		lea2 %1, ebp
	%else
		lea2 %1, ebp
		lea2 %1, edi
		lea2 %1, esi
		lea2 %1, edx
		lea2 %1, ecx
		lea2 %1, ebx
		lea2 %1, eax
	%endif
%endmacro

%macro lea2 arg(2)
	rget_maybe %2
	%if reg_val > -1
		%assign lea_delta %1-reg_val
		%if lea_delta < 128 && lea_delta > -129
			dbg 0, DELTA %1 %2 lea_delta
			%assign	lea_disp lea_delta
			%define lea_dbase %2
			rget %2
		%endif
		; base
		%if !LEA_PERPLEXITY
			lea3 %1, %2, eax
			lea3 %1, %2, ebx
			lea3 %1, %2, ecx
			lea3 %1, %2, edx
			lea3 %1, %2, esi
			lea3 %1, %2, edi
			lea3 %1, %2, esp
		%else
			lea3 %1, %2, esp
			lea3 %1, %2, edi
			lea3 %1, %2, esi
			lea3 %1, %2, edx
			lea3 %1, %2, ecx
			lea3 %1, %2, ebx
			lea3 %1, %2, eax
		%endif
	%endif
%endmacro

%macro lea3 arg(3)
	rget_maybe %3
	%assign %%base reg_val
	%assign dbglvl 0
	%assign LEA_MAX 0xffffffff

	%if reg_val > -1
		rget_maybe %2
		%assign %%index reg_val
		;dbg 0, LEA %2 %3 %%base + %%index == %1

		%if (%%base + %%index) & LEA_MAX == %1
			%define lea_base	%3
			%define lea_index	%2
			rget	%2
			rget	%3
			%assign lea_scale	1
			dbg dbglvl, LEA FOUND %2,%3 %%base + lea_scale * %%index
		%elif (%%base + (2*%%index)) & LEA_MAX == %1
			%define lea_base	%3
			%define lea_index	%2
			rget	%2
			rget	%3
			%assign lea_scale	2
			dbg dbglvl, LEA FOUND %2,%3 %%base + lea_scale * %%index
		%elif (%%base + (4*%%index)) & LEA_MAX == %1
			%define lea_base	%3
			%define lea_index	%2
			rget	%2
			rget	%3
			%assign lea_scale	4
			dbg dbglvl, LEA FOUND %2,%3 %%base + lea_scale * %%index
		%elif (%%base + (8*%%index)) & LEA_MAX == %1
			%define lea_base	%3
			%define lea_index	%2
			rget	%2
			rget	%3
			%assign lea_scale	8
			dbg dbglvl, LEA FOUND %2,%3 %%base + lea_scale * %%index
		%endif
	%endif

%endmacro
