%ifndef DEBUG
%define DEBUG 0
%endif

%ifndef SC_DEBUG
%define SC_DEBUG 0
%endif

%define SYS_memfd_secret	447
%define SYS_arch_prctl		384
%define SYS_execveat		358
%define SYS_recvfrom		371
%define SYS_sendto		369
%define SYS_setsockopt		366
%define SYS_accept4		364
%define SYS_listen		363
%define SYS_connect		362
%define SYS_bind		361
%define SYS_socket		359
%define SYS_memfd_create	356
%define SYS_seccomp		354
%define SYS_splice		313
%define SYS_unshare		310
%define SYS_clock_settime	264
%define SYS_exit_group		252
%define SYS_get_thread_area	244
%define SYS_set_thread_area	243
%define SYS_mmap		192
%define SYS_sendfile		187
%define SYS_capset		185
%define SYS_capget		184
%define SYS_prctl		172
%define SYS_nanosleep		162
%define SYS_mlockall		152
%define SYS_personality		136
%define SYS_fchdir		133
%define SYS_getdents		141
%define SYS_mprotect		125
%define SYS_clone		120
%define SYS_fstat		108
%define SYS_oldfstat		28
%define SYS_syslog		103
%define SYS_socketcall		102
%define SYS_ftruncate		93
%define SYS_munmap		91
%define SYS_reboot		88
%define SYS_settimeofday	79
%define SYS_gettimeofday	78
%define SYS_sigaction		67
%define SYS_getppid		64
%define SYS_dup2		63
%define SYS_chroot		61
%define SYS_ioctl		54
%define SYS_signal		48
%define SYS_brk			45
%define SYS_dup			41
%define SYS_kill		37
%define SYS_pause		29
%define SYS_alarm		27
%define SYS_ptrace		26
%define SYS_getuid		24
%define SYS_setuid		213
%define SYS_setgid		214
%define SYS_setresuid16		164
%define SYS_setfsuid16		138
%define SYS_setreuid16		70
%define SYS_getpid		20
%define SYS_stat		18
%define SYS_time		13
%define SYS_chdir		12
%define SYS_execve		11
%define SYS_unlink		10
%define SYS_creat		8
%define SYS_waitpid		7
%define SYS_close		6
%define SYS_open		5
%define SYS_openat2		437
%define SYS_write		4
%define SYS_read		3
%define SYS_fork		2
%define SYS_exit		1

%define STDIN			0
%define STDOUT			1
%define STDERR			2

%define O_RDONLY		0
%define O_WRONLY		1
%define O_RDWR			2
%define O_TRUNC			512
%define O_CREAT			64
%define O_CLOEXEC		0x80000
%define AT_FDCWD		-100
%define RESOLVE_BENEATH		0x08
%define RESOLVE_NO_XDEV         0x01 ; Block mount-point crossings
                                     ;   (includes bind-mounts).
%define RESOLVE_NO_MAGICLINKS   0x02 ; Block traversal through procfs-style
                                     ;   "magic-links".
%define RESOLVE_NO_SYMLINKS     0x04 ; Block traversal through all symlinks
                                     ;   (implies OEXT_NO_MAGICLINKS)
%define RESOLVE_BENEATH         0x08 ; Block "lexical" trickery like
                                     ;   "..", symlinks, and absolute
                                     ;   paths which escape the dirfd.
%define RESOLVE_IN_ROOT         0x10 ; Make all jumps to "/" and ".."
                                     ;   be scoped inside the dirfd
                                     ;   (similar to chroot(2)).
%define RESOLVE_CACHED          0x20 ; Only complete if resolution can be
                                     ;   completed through cached lookup. May
                                     ;   return -EAGAIN if that's not
                                     ;   possible.

%define CLOCK_REALTIME		0

%define PTRACE_SEIZE		0x4206
%define PTRACE_ATTACH		0x10
%define PTRACE_GETREGS		12
%define PTRACE_SETREGS		13
%define PTRACE_POKETEXT		4
%define PTRACE_DETACH		17
%define PTRACE_CONT		7
%define PTRACE_O_EXITKILL	0x100000
%define PR_SET_DUMPABLE		4
%define PR_SET_NAME		15
%define PR_CAP_AMBIENT		47
%define PR_CAP_AMBIENT_RAISE	2
%define PR_GET_SECUREBITS	27
%define PR_SET_SECUREBITS	28
%define PR_SET_MM		35
%define PR_SET_MM_EXE_FILE	13
%define PR_SET_MM_MAP		14
%define PR_SET_MM_MAP_SIZE	15
%define PR_SET_NO_NEW_PRIVS	38
%define PR_SET_VMA		0x53564d41
%define PR_SET_VMA_ANON_NAME	0

%define PR_SET_KEEPCAPS		8
%define SECBIT_KEEP_CAPS	16



%define CLONE_NEWUSER		0x10000000
%define CLONE_VM		0x00000100
%define CLONE_THREAD		0x00010000
%define CLONE_SIGHAND		0x00000800
%define CLONE_THREADALL		CLONE_VM | CLONE_SIGHAND | CLONE_THREAD


%define	MAP_SHARED		0x01
%define	MAP_PRIVATE		0x02
%define	MAP_SHARED_VALIDATE	0x03
%define	MAP_FIXED		0x10
%define	MAP_FIXED_NOREPLACE	0x100000
%define	MAP_ANONYMOUS		0x20
%define	MAP_ANON		MAP_ANONYMOUS
%define PROT_READ		0x1
%define PROT_WRITE		0x2
%define PROT_EXEC		0x4

%define TIOCSWINSZ		0x5414

%define AT_EMPTY_PATH		0x1000

%assign sc_arg1_type 0
%assign sc_arg2_type 0
%assign sc_arg3_type 0
%assign sc_arg4_type 0
%assign sc_arg5_type 0
%assign sc_arg6_type 0

%imacro sc_param 3
	%deftok %%f %strcat("sc_arg",%str(%3),"_type")
	%ifempty %2
		;%warning uhoh empty __LINE__, %0 %1 %2, pass __PASS__
	%elif %%f && %isstr(%2)
		%if %%f == 1
			string0 %1, %2
		%elif %%f == 2
			;%fatal UUUUU %1 %2
			string %1, %2
		%else
			%error %?: unknown type %%f 
		%endif
		%assign %%f 0
	%elifidn %2,x
		;%warning uhoh x __LINE__, %0 %1 %2, pass __PASS__
	%elifidn %2,pop
		;%warning uhoh pop __LINE__, %0 %1 %2, pass __PASS__
		pop	%1
		taint	%1
	%elifidn %2,esp
		realesp %1
	%elifidn %2,eax
		%warning syscall EAX parameter, using ychg
		; TODO: not if eax == sc_nr
		ychg	%1, %2
	%else
		%warning %?: sc_param set %1 == %2
		;rdump
		set	%1, %2
	;%else
	;	%warning uhoh else __LINE__ %0 %1 %2, pass __PASS__
	%endif
%endmacro

%imacro sc_setnr 1
	set	sc_nr, %1
%endmacro

%imacro sc_exec 0
	%ifndef ALT_SYSCALL
		int	0x80
		taint	sc_nr
	%else
		call	ebp
	%endif
%endmacro

%define sc_nr		eax
%define sc_ret		eax
%define sc_stack	esp
%define sc_arg1		ebx
%define sc_arg2		ecx
%define sc_arg3		edx
%define sc_arg4		esi
%define sc_arg5		edi
%define sc_arg6		ebp

%imacro syscall arg(1-7)
	return_reg sc_ret
	;reg_push
	%warning SYSCALL%0 1:%1 2:%2 3:%3 4:%4 5:%5 6:%6 7:%7

	%if %0 > 1
		sc_param sc_arg1, %2, 1
	%endif
	%if %0 > 2
		sc_param sc_arg2, %3, 2
	%endif
	%if %0 > 3
		sc_param sc_arg3, %4, 3
	%endif
	%if %0 > 4
		sc_param sc_arg4, %5, 4
	%endif
	%if %0 > 5
		sc_param sc_arg5, %6, 5
	%endif
	%if %0 > 6
		sc_param sc_arg6, %7, 6
	%endif
	sc_setnr	%1
	%warning SYSCALL%0 %1
	;reg_commit
	%if SC_DEBUG
		reg
	%endif
	sc_exec
	%if SC_DEBUG
		reg
	%endif

%endmacro

%macro expect arg(1)
	rset	sc_ret, %1
%endmacro

%imacro realesp arg(1)
	%ifndef FAKESTACK
		set     %1, esp
	%else
		%%fakestack:
		mov     %1, FAKESTACK
		add     %1, esp
		taint   %1
	%endif
%endmacro

%imacro sleep arg(1)
	push0
	push	%1
	syscall	SYS_nanosleep, esp
	%if stack_cleanup
		pop	sc_arg1
		pop	sc_arg1
		rset	sc_arg1, 0
	%endif
%endmacro

%imacro fork arg(0)
	syscall SYS_fork
%endmacro

%imacro clone arg(5)
	syscall SYS_clone, %1, %2, %3, %4, %5
%endmacro

%imacro clone arg(2)
	syscall SYS_clone, %1, %2
%endmacro

%imacro splice arg(5)
	syscall SYS_splice, %1, %2, %3, %4, %5
%endmacro

%imacro unshare arg(1)
	syscall SYS_unshare, %1
%endmacro

%imacro kill arg(2)
	syscall SYS_kill, %1, %2
%endmacro

%imacro raise arg(1)
	getpid
	ychg	sc_ret, sc_arg1
	kill	x, %1
%endmacro

%imacro getuid arg(0)
	syscall SYS_getuid
%endmacro

%imacro setuid arg(1)
	syscall SYS_setuid, %1
%endmacro

%imacro setgid arg(1)
	syscall SYS_setgid, %1
%endmacro

%imacro setresuid16 arg(3)
	syscall SYS_setresuid16, %1, %2, %3
%endmacro

%imacro setfsuid16 arg(1)
	syscall SYS_setfsuid16, %1
%endmacro

%imacro setreuid16 arg(2)
	syscall SYS_setreuid16, %1, %2
%endmacro

%imacro getppid arg(0)
	syscall SYS_getppid
%endmacro

%imacro getpid arg(0)
	syscall SYS_getpid
	rset	sc_ret, -4
%endmacro

%imacro waitpid arg(3)
	syscall SYS_waitpid, %1, %2, %3
%endmacro

%imacro wait arg(0)
	waitpid	0, 0, 0
%endmacro

%imacro ptrace arg(4)
	syscall SYS_ptrace, %1, %2, %3, %4
%endmacro

%imacro arch_prctl arg(2)
	syscall SYS_arch_prctl, %1, %2
%endmacro

%imacro setfs arg(1)
	arch_prctl 0x1002, %1
%endmacro

%imacro setgs arg(1)
	arch_prctl 0x1001, %1
%endmacro

%imacro execve arg(3)
	%assign sc_arg1_type 1
	syscall SYS_execve, %1, %2, %3
%endmacro

%imacro execveat arg(5)
	%assign sc_arg1_type 1
	syscall SYS_execveat, %1, %2, %3, %4, %5
%endmacro

%imacro system3 arg(1)
	%ifstr %1
		inline_str %strcat(%1,`\0`)
		pop	ecx
		taint	ecx
		%define SYSTEM_INPUT ecx
	%else
		%define SYSTEM_INPUT %1
	%endif
        push `-c\0\0`
        mov     eax, esp
	taint	eax
        push `/sh\0`
        push `/bin`

        mov     ebx, esp
        push    0
        push    SYSTEM_INPUT
        push    eax
        push    ebx

        execve ebx, esp, 0
%endmacro

%imacro system arg(1)
	envp	edx
	%ifstr %1
		inline_str %strcat(%1,`\0`)
		pop	ecx
		taint	ecx
		%define SYSTEM_INPUT ecx
	%else
		%define SYSTEM_INPUT %1
	%endif
        push `-c\0\0`
        mov     eax, esp
	taint	eax
        push `/sh\0`
        push `/bin`

        mov     ebx, esp
        push    0
        push    SYSTEM_INPUT
        push    eax
        push    ebx

        execve ebx, esp, edx
%endmacro

%imacro system2 arg(1)
SECTION .data follows=.text
SH:    db '/bin/sh', 0
SHC:   db '-c', 0
SECTION .text
	%ifstr %1
		inline_str %strcat(%1,`\0`)
		pop	ecx
		taint	ecx
		%define SYSTEM_INPUT ecx
	%else
		%define SYSTEM_INPUT %1
	%endif

        push    0
        push    SYSTEM_INPUT
        push    SH
        push    SHC

        execve SH, esp, 0
%endmacro

%imacro capget arg(2)
	syscall SYS_capget, %1, %2
%endmacro

%imacro capset arg(2)
	syscall SYS_capset, %1, %2
%endmacro

%imacro prctl arg(1)
	syscall SYS_prctl, %1
%endmacro

%imacro prctl arg(2)
	syscall SYS_prctl, %1, %2
%endmacro

%imacro prctl arg(3)
	syscall SYS_prctl, %1, %2, %3
%endmacro

%imacro prctl arg(4)
	syscall SYS_prctl, %1, %2, %3, %4
%endmacro

%imacro prctl arg(5)
	syscall SYS_prctl, %1, %2, %3, %4, %5
%endmacro

%imacro reboot arg(3)
	syscall SYS_reboot, %1, %2, %3
%endmacro

%imacro seccomp arg(3)
	syscall SYS_seccomp, %1, %2, %3
%endmacro

%imacro memfd_secret arg(0)
	syscall SYS_memfd_secret, O_CLOEXEC
%endmacro

%imacro memfd_create arg(2)
	syscall SYS_memfd_create, %1, %2
%endmacro

%imacro ftruncate arg(2)
	syscall SYS_ftruncate, %1, %2
%endmacro

%imacro clock_settime arg(2)
	syscall SYS_clock_settime, %1, %2
%endmacro

%imacro settimeofday arg(1)
	syscall SYS_settimeofday, %1, 0
%endmacro

%imacro gettimeofday arg(1)
	syscall SYS_gettimeofday, %1, 0
%endmacro

%imacro	settime arg(1)
	push	0
	push	%1
	clock_settime CLOCK_REALTIME, esp
%endmacro

%imacro time arg(0)
	syscall SYS_time, 0
%endmacro

%imacro pause arg(0)
	syscall SYS_pause
%endmacro

%imacro alarm arg(1)
	syscall SYS_alarm, %1
%endmacro

%imacro mprotect arg(3)
	syscall SYS_mprotect, %1, %2, %3
%endmacro


%define	SIG_DFL	0
%define	SIG_IGN	1

%macro signal arg(2)
	push0
	push0
	push	%2
	syscall	SYS_sigaction, %1, esp, 0
	%if stack_cleanup
		pop	ecx
		pop	ecx
		pop	ecx
		rset	ecx, 0
		; ecx, edx = 0
	%endif
%endmacro

%macro sigign arg(1)
	syscall	SYS_signal, %1, 1
%endmacro

%macro brk arg(0-1) 0
	syscall	SYS_brk, %1
%endmacro

%macro sbrk arg(2)
	brk
	lea	sc_arg1, [sc_ret+%2]
	;%ifnidn	sc_ret, %1
		ychg	sc_ret, %1
	;%endif
	taint	sc_arg1
	brk	sc_arg1
%endmacro

%macro sbrk2 arg(2)
	brk
	set	ecx, %2
	lea	sc_arg1, [sc_ret+ecx]
	ychg	sc_ret, %1
	taint	sc_arg1
	brk	sc_arg1
%endmacro

%macro sbrk3 arg(2)
	brk
	set	sc_arg1, %2
	add	sc_arg1, sc_ret
	taint	sc_arg1
	ychg	%1, sc_ret
	brk	sc_arg1
%endmacro

%imacro mmap arg(6)
	syscall SYS_mmap, %1, %2, %3, %4, %5, %6
%endmacro

; but there is no free
%imacro malloc arg(1)
	rget	edx
	%if reg_val > 0 && (reg_val & 3 == 3)
		%warning malloc: edx ok: reg_val
	%else
		mov	dl, PROT_READ|PROT_WRITE
	%endif
	taint	edx

	mmap	x, %1, x, MAP_PRIVATE|MAP_ANONYMOUS, x, x
%endmacro

%imacro munmap arg(2)
	syscall SYS_munmap, %1, %2
%endmacro

%imacro mlockall arg(1)
	syscall SYS_mlockall, %1
%endmacro

%imacro chdir arg(1)
	%assign sc_arg1_type 1
	syscall SYS_chdir, %1
%endmacro

%imacro fchdir arg(1)
	syscall SYS_fchdir, %1
%endmacro

%imacro personality arg(1)
	syscall SYS_personality, %1
%endmacro

%imacro exit arg(0-1) 0
	%if 1 && REG_OPT_LEVEL > 3
		rget sc_nr
		%if reg_val != SYS_exit
			reg_search SYS_exit
			%if reg_search_match != 0
				rget reg_search_match
				ychg	sc_nr, reg_search_match
			%endif
		%endif
	%elif 0 && REG_OPT_LEVEL > 3
		%warning EXIT %0 %1
		rget sc_arg1
		%warning EXIT arg1 reg_val
		%if reg_val == SYS_exit
			%warning EXIT match arg1 reg_val
			rget sc_nr
			%warning EXIT nr reg_val
			%if reg_val != %1
				%warning EXIT match nr reg_val
				reg_search %1
				%if reg_search_match != 0
					rget reg_search_match
					ychg	sc_nr, reg_search_match
					reg_search SYS_exit
					%if reg_search_match != 0
						rget reg_search_match
						ychg	sc_nr, reg_search_match
					%endif
				%endif
			%endif
		%elif reg_val != SYS_exit
			reg_search SYS_exit
			%if reg_search_match != 0
				rget reg_search_match
				ychg	sc_nr, reg_search_match
			%endif
		%endif

	%elif 1 && REG_OPT_LEVEL > 3
		%warning EXIT %0 %1
		rget sc_nr
		%if reg_val != %1
			rget sc_arg1
			%if reg_val != SYS_exit
				reg_search %1
				%if reg_search_match != 0
					rget reg_search_match
					ychg	sc_nr, reg_search_match
					reg_search SYS_exit
					%if reg_search_match != 0
						rget reg_search_match
						ychg	sc_nr, reg_search_match
					%endif
				%endif
			%endif
		%elif reg_val != SYS_exit
			reg_search SYS_exit
			%if reg_search_match != 0
				rget reg_search_match
				ychg	sc_nr, reg_search_match
			%endif
		%endif
	%endif
	syscall SYS_exit, %1
%endmacro

%imacro exit_group arg(0-1) 0
	syscall SYS_exit_group, %1
%endmacro

%imacro get_thread_area arg(1)
	syscall SYS_get_thread_area, %1
%endmacro

%imacro set_thread_area arg(1)
	syscall SYS_set_thread_area, %1
%endmacro

%imacro ioctl arg(3)
	syscall SYS_ioctl, %1, %2, %3
%endmacro

%imacro setwinsize arg(2)
	push0
	push	%1*256*256 + %2
	ioctl	0, TIOCSWINSZ, esp
	%if stack_cleanup
		pop	edx
		pop	edx
		rset	edx, 0
	%endif
%endmacro

%imacro setsockopt arg(5)
	syscall SYS_setsockopt, %1, %2, %3, %4, %5
%endmacro

%imacro listen arg(2)
	syscall SYS_listen, %1, %2
%endmacro

%imacro socket arg(2-3) 0
	syscall SYS_socket, %1, %2, %3
%endmacro

%imacro accept4 arg(4)
	syscall SYS_accept4, %1, %2, %3, %4
%endmacro

%imacro bind arg(3)
	syscall SYS_bind, %1, %2, %3
%endmacro

%imacro connect arg(3)
	syscall SYS_connect, %1, %2, %3
%endmacro

%imacro sendto arg(6)
	%assign sc_arg2_type 2
	syscall SYS_sendto, %1, %2, %3, %4, %5, %6
%endmacro

%imacro recvfrom arg(6)
	syscall SYS_recvfrom, %1, %2, %3, %4, %5, %6
%endmacro

%imacro syslog arg(3)
	syscall SYS_syslog, %1, %2, %3
%endmacro

%imacro unlink arg(1)
	%assign sc_arg1_type 1
	syscall SYS_unlink, %1
%endmacro

%imacro open arg(2)
	%assign sc_arg1_type 1
	syscall SYS_open, %1, %2
%endmacro

%imacro open arg(3)
	%assign sc_arg1_type 1
	syscall SYS_open, %1, %2, %3
%endmacro

%imacro openat2 arg(4)
	%assign sc_arg1_type 1
	syscall SYS_openat2, %1, %2, %3, %4
%endmacro

;%imacro openat2 arg(3)
;	openat %1, %2, %3, 24
;%endmacro

%imacro creat arg(2)
	%assign sc_arg1_type 1
	syscall SYS_creat, %1, %2
%endmacro

%imacro close arg(1)
	syscall SYS_close, %1
%endmacro

%imacro getdents arg(3)
	syscall SYS_getdents, %1, %2, %3
%endmacro

%imacro sendfile arg(4)
	syscall SYS_sendfile, %1, %2, %3, %4
%endmacro

%imacro fstat arg(2)
	syscall SYS_fstat, %1, %2
%endmacro

%imacro oldfstat arg(2)
	syscall SYS_oldfstat, %1, %2
%endmacro

%imacro stat arg(2)
	syscall SYS_stat, %1, %2
%endmacro

%imacro dup arg(1)
	syscall SYS_dup, %1
%endmacro

%imacro dup2 arg(2)
	syscall SYS_dup2, %1, %2
%endmacro

%imacro chroot arg(1)
	%assign sc_arg1_type 1
	syscall SYS_chroot, %1
%endmacro

%imacro read arg(3)
	syscall SYS_read, %1, %2, %3
%endmacro

%imacro write arg(3)
	%assign sc_arg2_type 2
	syscall SYS_write, %1, %2, %3
%endmacro

